# SERVER
server:
  port: 56578
  servlet:
    contextPath: /api/v1

# SPRING
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: @project.artifactId@
    version: @project.version@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: ${dbURL}
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-bean-definition-overriding: true

# SPRING ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
        
#logging.level.org.apache.http: DEBUG
#logging.level.org.springframework.web.client.RestTemplate: DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor: DEBUG
#logging.level.ROOT: DEBUG

jwt:
  secretKey: ${jwtSecretKey}}
  refreshSecretKey: ${jwtRefreshSecretKey}}

timeouts:
  MAX_TOTAL_CONNECTIONS: 5
  CONNECT_TIMEOUT: 9000
  REQUEST_TIMEOUT: 9000
  SOCKET_TIMEOUT: 9000
  CONN_TIME_TO_LIVE: 15
  VALIDATE_AFTER_INACTIVITY: 5
  DEFAULT_MAX_PER_ROUTE: 5
  THREAD_TIMEOUT: 5000
  IDLE_TIMEOUT: 30        
        
restTemplate:
